### ISSUE TITLE
Create a template for common parameters

### ISSUE THREAD

**Issue by rengolin** [Linaro/hpc_lab_jenkins#68]
Some parameters may change, and if other labs will want to use this infrastructure, we need to move the lab-specific stuff into configuration files.

Some things that need to be looked at:
 * IP address & port for MrP, file-server, etc. The client makes extensive use of it.
 * Which machines belong to each node list for each job
   * Listing all would be counterproductive to any lab
 * Authorisation list in jobs (do we even need it at the Job level, if all are the same?)
 * User. We default to `root` but that might not be required/wanted by other labs
 * How many nodes each cluster has and which compute names they have
 * OpenHPC components list to install/enable/test

Other things that may not be able to change:
 * User directories (ex. `/home/d03bench`), because this is required by Jenkins
 * Machine names (ex. `tx2bench`) because that's exclusive to MrP (no DNS), so can be anything
   * And we need names to be meaningful, like {arch}{type}, to infer node types, etc.
   * At least we need to assume the style is consistent, whatever the {arch}s and {type}s are

**Comment by BaptisteGerondeau** [comment]
```yaml
clusters:
    - type: qdc
      node: qdcohpc
      machine_list:
          - qdcohpc
          - qdc01
          - qdc02
          - qdc03
      machine_types:
          - qdc
          - qdc
          - qdc
          - qdc

    - type: d05
      node: d05ohpc
      machine_list:
          - d05ohpc
          - d0301
          - d0302
          - d0303
      machine_types:
          - d05
          - d03
          - d03
          - d03
      
machine_parameters:
    - type: d03
      arch: AArch64
      subarch: Grub
      kernel_opts: "modprobe.blacklist=hibmc_drm earlycon console=ttyS0,115200"
      os_type: centos

    - type: d05
      arch: AArch64
      subarch: Grub
      kernel_opts: "earlycon console=ttyAMA0,115200"
      os_type: centos

    - type: qdc
      arch: AArch64
      subarch: GrubWithOptionEfiboot
      kernel_opts: "earlycon console=ttyAMA0,115200"
      os_type: centos-upstream

os_parameters:
    - type: debian
      preseed_type: preseed
      kernel_desc: "Debian ERP 18.06"
      initrd_desc: "Debian ERP 18.06"
      preseed_name: "Debian"
      kernel_opts: ""

    - type: centos
      preseed_type: kickstart
      kernel_desc: "CentOS ERP 18.06"
      initrd_desc: "CentOS ERP 18.06"
      preseed_name: "CentOS"
      kernel_opts: "ip=dhcp text inst.stage2=http://10.40.0.13/releases.linaro.org/reference-platform/enterprise/18.06/centos-installer/ inst.repo=http://10.40.0.13/mirror.centos.org/altarch/7/os/aarch64/ inst.ks=file:/ks.cfg"

    - type: centos-upstream
      preseed_type: kickstart
      kernel_desc: "CentOS 7.5"
      initrd_desc: "CentOS 7.5"
      preseed_name: "CentOS Upstream"
      kernel_opts: "ip=dhcp text inst.stage2=http://10.40.0.13/mirror.centos.org/altarch/7/os/aarch64/ inst.repo=http://10.40.0.13/mirror.centos.org/altarch/7/os/aarch64/ inst.ks=file:/ks.cfg"
```

This kind of configuration file ?
